"""
schema.py

State definitions shared across all LangGraph nodes.
"""

from typing import List, Dict, Any, Optional

from typing_extensions import TypedDict

import pandas as pd


class GraphState(TypedDict):

    # Original user request
    user_query: str

    # Planner output
    planned_steps: List[str]

    # Reflected database schema
    database_schema: str

    # SQL generated by the SQL specialist
    generated_sql: str

    # Validator feedback
    validation_error: Optional[str]

    # SQL execution results
    dataframe: Optional[pd.DataFrame]

    # Metadata about the DataFrame
    dataframe_schema: Dict[str, str]

    # Generated Plotly code
    plotly_code: str

    # Plotly Figure object
    figure: Any

    # Executive summary
    final_response: str

    # Conversation history
    messages: List[Dict[str, str]]

    # Retry counter
    retry_count: int

    # Error messages
    error: Optional[str]